### ISSUE TITLE
Hitting "enter" on blank input field provides a doppl for quit_cryan

### ISSUE THREAD

**Issue by tHartman77** [tHartman77/doppel#2]
If you hit enter without typing anything in the input field, it provides a doppl for the account quit_cryan. It always does it for this account even if you type something, then remove the text, and hit enter again.

**Comment by rym23** [comment]
Really odd, I don't see the account name in the code anywhere.  I wonder if heroku has a different version than we do.

**Comment by tHartman77** [comment]
Fixed this by checking if the field is empty in jquery.
